version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:7.0
    container_name: dealership-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: DealershipDB
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - dealership-network

  # Application service
  dealership-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dealership-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - MongoDb__ConnectionString=mongodb://mongodb:27017/DealershipDB
      - MongoDb__DatabaseName=DealershipDB
      - MongoDb__CarsCollectionName=Cars
      - MongoDb__InvoicesCollectionName=Invoices
    depends_on:
      - mongodb
    volumes:
      - ./wwwroot/invoices:/app/wwwroot/invoices
    networks:
      - dealership-network

volumes:
  mongodb_data:
    driver: local

networks:
  dealership-network:
    driver: bridge
